/**:
  ros__parameters:
    joints_map:
      left_front:
        - FL_hip_joint
        - FL_uleg_joint
        - FL_lleg_joint
        - FL_foot_fixed

      right_front:
        - FR_hip_joint
        - FR_uleg_joint
        - FR_lleg_joint
        - FR_foot_fixed

      left_hind:
        - BL_hip_joint
        - BL_uleg_joint
        - BL_lleg_joint
        - BL_foot_fixed

      right_hind:
        - BR_hip_joint
        - BR_uleg_joint
        - BL_lleg_joint
        - BR_foot_fixed
