controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - FL_hip_joint
        - FL_uleg_joint
        - FL_lleg_joint
        - FR_hip_joint
        - FR_uleg_joint
        - FR_lleg_joint
        - BL_hip_joint
        - BL_uleg_joint
        - BL_lleg_joint
        - BR_hip_joint
        - BR_uleg_joint
        - BR_lleg_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    
    gains:
      # PID Uniforme para todas las articulaciones
      FL_hip_joint        : {p: 45.0, i: 4.5, d: 0.5}
      FR_hip_joint        : {p: 45.0, i: 4.5, d: 0.5}
      BL_hip_joint        : {p: 45.0, i: 4.5, d: 0.5}
      BR_hip_joint        : {p: 45.0, i: 4.5, d: 0.5}

      FL_uleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
      FR_uleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
      BL_uleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
      BR_uleg_joint       : {p: 45.0, i: 4.5, d: 0.5}

      FL_lleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
      FR_lleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
      BL_lleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
      BR_lleg_joint       : {p: 45.0, i: 4.5, d: 0.5}
