controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - FL_hip_joint
        - FL_uleg_joint
        - FL_lleg_joint
        - FR_hip_joint
        - FR_uleg_joint
        - FR_lleg_joint
        - BL_hip_joint
        - BL_uleg_joint
        - BL_lleg_joint
        - BR_hip_joint
        - BR_uleg_joint
        - BR_lleg_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    
    gains:
      # Caderas (Hip joints)
      FL_hip_joint        : {p: 63.69, i: 6.37, d: 0.22}
      FR_hip_joint        : {p: 63.69, i: 6.37, d: 0.22}
      BL_hip_joint        : {p: 63.69, i: 6.37, d: 0.22}
      BR_hip_joint        : {p: 63.69, i: 6.37, d: 0.22}
      
      # Rodillas superiores (Upper leg joints)
      FL_uleg_joint       : {p: 31.85, i: 3.19, d: 0.44}
      FR_uleg_joint       : {p: 31.85, i: 3.19, d: 0.44}
      BL_uleg_joint       : {p: 31.85, i: 3.19, d: 0.44}
      BR_uleg_joint       : {p: 31.85, i: 3.19, d: 0.44}

      # Rodillas inferiores (Lower leg joints)
      FL_lleg_joint       : {p: 38.20, i: 3.82, d: 0.37}
      FR_lleg_joint       : {p: 38.20, i: 3.82, d: 0.37}
      BL_lleg_joint       : {p: 38.20, i: 3.82, d: 0.37}
      BR_lleg_joint       : {p: 38.20, i: 3.82, d: 0.37}