controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - FL_hip_joint
        - FL_uleg_joint
        - FL_lleg_joint
        - FR_hip_joint
        - FR_uleg_joint
        - FR_lleg_joint
        - BL_hip_joint
        - BL_uleg_joint
        - BL_lleg_joint
        - BR_hip_joint
        - BR_uleg_joint
        - BR_lleg_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    
    gains:
      FL_hip_joint        : {p: 15.0, i: 0.0, d: 0.005}
      FL_uleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      FL_lleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      FR_hip_joint        : {p: 15.0, i: 0.0, d: 0.005}
      FR_uleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      FR_lleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      BL_hip_joint        : {p: 15.0, i: 0.0, d: 0.005}
      BL_uleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      BL_lleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      BR_hip_joint        : {p: 15.0, i: 0.0, d: 0.005}
      BR_uleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      BR_lleg_joint       : {p: 15.0, i: 0.0, d: 0.005}
      
      # {p: 67.5, d: 0.3, i: 0.1, i_clamp: 1.5}
    # action_monitor_rate: 10.0 # Defaults to 20
    # state_publish_rate: 10.0 # Defaults to 50
    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

# joint_group_position_controller:
#   ros__parameters:
#     use_sim_time: True
#     type: joint_trajectory_controller/JointTrajectoryController
#     joints:
#         - lf_hip_joint
#         - lf_upper_leg_joint
#         - lf_lower_leg_joint
#         - rf_hip_joint
#         - rf_upper_leg_joint
#         - rf_lower_leg_joint
#         - lh_hip_joint
#         - lh_upper_leg_joint
#         - lh_lower_leg_joint
#         - rh_hip_joint
#         - rh_upper_leg_joint
#         - rh_lower_leg_joint 
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
    
#     # state_publish_rate: 25.0 # Defaults to 50
#     # action_monitor_rate: 10.0 # Defaults to 20
#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)
    # gains:
    #     lf_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     lf_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     lf_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     rf_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     rf_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     rf_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     lh_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     lh_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     lh_lower_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     rh_hip_joint        : {p: 180, d: 0.9, i: 20}
    #     rh_upper_leg_joint  : {p: 180, d: 0.9, i: 20}
    #     rh_lower_leg_joint  : {p: 180, d: 0.9, i: 20}

